steps:
  - name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']
images: ['gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
      args: ['set', 'image', 'deployment/my-app-deployment', 'my-app-container=gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '-n', 'default']
  - name: 'gcr.io/cloud-builders/kubectl'
      args: ['rollout', 'restart', 'deployment/my-app-deployment', '-n', 'default']
      images: ['gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']
